CSRF_ENABLED = True
SECRET_KEY = '0000000000000000'

# MySQL
SQLALCHEMY_DATABASE_URI = 'mysql://username:password@localhost/parkomat'
SQLALCHEMY_TRACK_MODIFICATIONS = False

# Telegram
TELEGRAM_TOKEN = 'YOUR_TELEGRAM_TOKEN'
TELEGRAM_CHAT_ID = 'CHANNEL_ID'
